service: repomanager
frameworkVersion: '2'

useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: production
  logRetentionInDays: 3
  usagePlan:
    quota:
      limit: 5000
      period: MONTH
    throttle:
      burstLimit: 50
      rateLimit: 10

  environment:
    APP_ID: ${env:APP_ID}
    GITHUB_WEBHOOK_SECRET: ${env:GITHUB_WEBHOOK_SECRET}
    CERT: ${env:CERT}

functions:
  # githubWebhookListener:
  #   handler: handler.githubWebhookListener
  #   events:
  #     - http:
  #         path: webhook
  #         method: post
  #         cors: true

  cron:
    handler: handler.cron
    timeout: 360
    memorySize: 256
    events:
      - schedule: rate(10 minutes)

package:
  exclude:
    - test/**
    - .*
    - .*/**
    - coverage/**
    - Dockerfile
    - '*.md'
    - '*.pem'
    - LICENSE
    - package*
    - wallaby.js
