service: repomanager
frameworkVersion: "4"

useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  stage: production
  logRetentionInDays: 3

  environment:
    APP_ID: ${env:APP_ID}
    GITHUB_WEBHOOK_SECRET: ${env:GITHUB_WEBHOOK_SECRET}
    CERT: ${env:CERT}

functions:
  # githubWebhookListener:
  #   handler: handler.githubWebhookListener
  #   events:
  #     - http:
  #         path: webhook
  #         method: post
  #         cors: true

  cron:
    handler: handler.cron
    timeout: 360
    memorySize: 256
    events:
      - schedule: rate(10 minutes)

package:
  exclude:
    - test/**
    - .*
    - .*/**
    - coverage/**
    - Dockerfile
    - "*.md"
    - "*.pem"
    - LICENSE
    - package*
    - wallaby.js
    - jest.config.js
    - eslint.config.mjs
    - ./__tests__/**
    - ./**/*.d.ts
    - ./**/*.js.map
    - ./node_modules/**/dist-web/**
    - ./node_modules/**/dist-src/**
    - ./node_modules/**/README.md
    - ./node_modules/**/LICENSE
    - ./node_modules/**/browser/**