name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".nvmrc"

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: NPM Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: NPM Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # master
        with:
          github-token: ${{ secrets.github_token }}

      - uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
        with:
          use-installer: true

      - name: SAM build
        run: sam build

      - name: SAM validate
        run: sam validate --lint

      - name: Tar files
        run: tar -cf dist.tar .aws-sam template.yaml handler.js src scripts base-repo-config.yml package.json package-lock.json

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist.tar
          path: dist.tar

  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - build
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist.tar
      - run: tar -xf dist.tar

      - uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6
        with:
          role-to-assume: arn:aws:iam::557195821817:role/repomanager-update
          role-session-name: repomanagerupdate
          aws-region: eu-west-2

      - name: SAM deploy
        run: |
          CERT_B64=$(printf '%s' "$CERT" | base64 -w0)
          sam deploy \
            --stack-name repomanager \
            --region eu-west-2 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --parameter-overrides \
              AppId=${{ secrets.APP_ID }} \
              GitHubWebhookSecret=${{ secrets.WEBHOOK_SECRET }} \
              "Cert=$CERT_B64"
        env:
          CERT: ${{ secrets.CERT }}
